language: node_js
node_js:
  - "10"
  - "12"
  - "13"
os:
  - linux
  - osx
  - windows
cache:
  directories:
    - node_modules
stages:
  - test
jobs:
  include:
    - stage: test
      node_js:
        - "12"
      os:
        - linux
      script:
        - npm run test:coverage
    - stage: test
      node_js:
        - "12"
      os:
        - linux
      script:
        - npm run lint
    - stage: test
      node_js:
        - "12"
      os:
        - linux
      script:
        - npm run check:type
